development:
  adapter: postgresql
  database: google_maps_ajax_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: google_maps_ajax_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: google_maps_ajax
  pool: 5
  timeout: 5000
